name: Build Docker image

on:
  push:
    branches: ["main"]
  
env:
  PROJECT_ID: globant-apescara
  REGION: us-central1
  ARTIFACT_REPO: us-central1-docker.pkg.dev/globant-apescara/globant-api

jobs:
  build-docker-img:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
      
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.ARTIFACT_REPO }}
        working-directory: .

      - name: Push image
        run: docker push ${{ env.ARTIFACT_REPO }}